version: '3'

services:
  sftp:
    build: .
    ports:
      - "8765:22"
    volumes:
      - ./config/users.conf:/etc/s3sftp/users.conf
      - ./config/buckets.conf:/etc/s3sftp/buckets.conf
      - ./config/keys/:/etc/ssh/keys
    environment:
      - ACCESS_KEY=$ACCESS_KEY
      - SECRET_KEY=$SECRET_KEY
      - S3_URL=$S3_URL
    # Those are necessary for fuse to mount inside the container
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined 
