version: '3'

services:
  sftp:
    image: ghcr.io/sacovo/s3sftp:main
    ports:
      - "8765:22"
    volumes:
      - ./config/users.conf:/etc/s3sftp/users.conf
      - ./config/buckets.conf:/etc/s3sftp/buckets.conf
      - ./keys/:/etc/ssh/keys
    environment:
      - ACCESS_KEY=your-access-key
      - SECRET_KEY=secret-key
      - S3_URL=https://s3-access-point.io
    # Those are necessary for fuse to mount inside the container
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined 
